export const SET_MEDIA_PLAY_NOW = "SET_MEDIA_PLAY_NOW";
export const SET_MEDIA_DURATION = "SET_MEDIA_DURATION";
export const SET_MEDIA_SOURCE = "SET_MEDIA_SOURCE";
export const SET_MEDIA_CURRENT_TIME = "SET_MEDIA_CURRENT_TIME";
export const SET_CHANGE_CURRENT_TIME = "SET_CHANGE_CURRENT_TIME";
export const CHANGE_PLAY_STATE = "CHANGE_PLAY_STATE";
export const CHANGE_CYCLE_MODE = "CHANGE_CYCLE_MODE";
export const CHANGE_MUTE_STATE = "CHANGE_MUTE_STATE";
